const UW = {
  hero: {
    title: 'The Ukraine War',
    subtitle: 'Europe\'s Largest Armed Conflict Since 1945',
    tagline: 'February 24, 2022 — Ongoing',
    eventStart: new Date('2022-02-24T05:00:00+02:00'),
  },

  stats: [
    { label: 'Civilian Deaths (UN Confirmed)', value: 10582, suffix: '+', icon: '⚰️', citation: 'UN OHCHR confirmed civilian deaths as of Jan 2026 (actual likely higher)' },
    { label: 'Refugees Across Europe', value: 8.2, suffix: 'M', icon: '🚶', citation: 'UNHCR — 8.2 million Ukrainian refugees recorded across Europe (mid-2024)' },
    { label: 'Internally Displaced', value: 3.7, suffix: 'M', icon: '🏠', citation: 'IOM — 3.7 million internally displaced persons within Ukraine (2024)' },
    { label: 'Front Line Length', value: 1200, suffix: 'km', icon: '⚔️', citation: '~1,200 km active front line from Kharkiv Oblast to Kherson Oblast (2024)' },
    { label: 'Military Aid to Ukraine', value: 267, suffix: 'B USD', icon: '💰', citation: 'Total international military & financial aid committed (Kiel Institute, Jan 2025)' },
    { label: 'Territory Occupied (Peak)', value: 27, suffix: '%', icon: '🗺️', citation: '~27% of Ukraine occupied at peak (Mar 2022); reduced to ~18% by mid-2024' },
  ],

  timeline: [
    { date: 'Feb 24, 2022', event: 'Full-Scale Invasion Begins',
      detail: 'Russia launches a multi-front invasion of Ukraine from Belarus, Crimea, and Russia. Missile strikes hit cities across the country. Ukrainian resistance immediately stiffens around Kyiv, Kharkiv, and Mariupol. The largest conventional war in Europe since 1945 begins.',
      quote: { text: '"We are here. We are in Ukraine. We will not give up. We will win."', source: 'Ukrainian President Volodymyr Zelenskyy, Feb 25, 2022' },
      image: 'Ukraine_War_Images/02_battle_of_kyiv_map.svg',
      tension: 10, type: 'invasion' },
    { date: 'Feb–Apr 2022', event: 'Battle of Kyiv — Russian Withdrawal',
      detail: 'Russian forces advance on Kyiv from the north but face fierce resistance in Hostomel, Irpin, and Bucha. Logistical failures, Ukrainian counterattacks, and poor Russian coordination halt the advance. By April 2, Russian forces withdraw from the Kyiv region, abandoning significant equipment.',
      quote: { text: '"If the Russians try to take Kyiv, they will meet a wall of fire."', source: 'Oleksiy Danilov, Secretary of Ukraine\'s NSDC, Mar 2022' },
      image: 'Ukraine_War_Images/03_invasion_overview_map.svg',
      tension: 9, type: 'battle' },
    { date: 'Mar 12 – May 20, 2022', event: 'Siege of Mariupol',
      detail: 'Mariupol is besieged and relentlessly bombarded for nearly three months. The Azovstal steel plant becomes the last redoubt of Ukrainian defenders and civilians. Over 20,000 civilians estimated killed. The city is reduced to rubble. On May 20, the last defenders surrender after running out of ammunition, food, and water.',
      quote: { text: '"They are all heroes. They defended their country, they defended the freedom of all of us. But this tragedy must come to an end."', source: 'Zelenskyy on Mariupol defenders, May 2022' },
      image: 'Ukraine_War_Images/05_russian_tanks_mariupol_4.jpg',
      tension: 10, type: 'siege' },
    { date: 'Apr 2, 2022', event: 'Bucha Massacre Discovered',
      detail: 'As Russian forces withdraw from the Kyiv suburbs, mass graves and evidence of summarily executed civilians are found in Bucha. International outcry follows. The UN later documents hundreds of unlawful killings. The event crystallises international perception of Russian war crimes and galvanises Western support for Ukraine.',
      quote: { text: '"Bucha will be forever a symbol of Russian cruelty and the inability of the world to stop evil."', source: 'Zelenskyy, Bucha visit, Apr 4, 2022' },
      image: 'Ukraine_War_Images/08_bucha_main_street.jpg',
      tension: 10, type: 'atrocity' },
    { date: 'Apr 14, 2022', event: 'Moskva Cruiser Sunk',
      detail: 'Ukrainian forces strike the Russian Black Sea Fleet flagship Moskva with Neptune anti-ship missiles. The cruiser sinks while being towed back to Sevastopol. It is the largest warship sunk in combat since World War II. The sinking severely damages Russian naval prestige and forces the Black Sea Fleet to operate from stand-off range.',
      quote: null,
      image: 'Ukraine_War_Images/09_russian_ship.jpg',
      tension: 8, type: 'combat' },
    { date: 'Sep 6 – Oct 2, 2022', event: 'Kharkiv Counteroffensive',
      detail: 'Ukrainian forces launch a surprise offensive in Kharkiv Oblast, shattering Russian defensive lines. Izyum, Kupiansk, and Lyman are liberated within weeks. The operation recaptures over 6,000 km² of territory — the most dramatic Ukrainian victory since the start of the war. It demonstrates that Russian forces can be beaten in open battle.',
      quote: { text: '"This is not a bluff. This is real. We are coming for you."', source: 'Ukrainian military social media post, Sep 2022' },
      image: 'Ukraine_War_Images/01_ukraine_map_cities.png',
      tension: 9, type: 'offensive' },
    { date: 'Sep 30, 2022', event: 'Russia Annexes Four Regions',
      detail: 'Russia formally annexes Donetsk, Luhansk, Zaporizhzhia, and Kherson oblasts after referendums widely condemned as shams. The annexation is legally void under international law. Putin declares: "This is the will of millions of people." Ukraine and the West reject the annexation and accelerate military aid.',
      quote: { text: '"We will continue to fight for our land. The borders of Ukraine are inviolable."', source: 'Zelenskyy, Sep 30, 2022' },
      image: 'Ukraine_War_Images/05_russian_occupied_territories_map.svg',
      tension: 9, type: 'diplomacy' },
    { date: 'Oct 8, 2022', event: 'Crimean Bridge Explosion',
      detail: 'A massive explosion damages the Kerch Strait Bridge linking Russia to occupied Crimea — a key supply route for Russian forces in southern Ukraine. Russia blames Ukraine (though Ukraine does not officially claim responsibility). In retaliation, Russia launches waves of missile strikes against Ukrainian energy infrastructure, beginning a campaign to leave Ukraine in darkness through winter.',
      quote: null,
      image: 'Ukraine_War_Images/03_occupied_territories.svg',
      tension: 8, type: 'sabotage' },
    { date: 'Nov 11, 2022', event: 'Liberation of Kherson',
      detail: 'Ukrainian forces liberate Kherson — the only regional capital Russia had captured since the invasion began. Russian forces withdraw across the Dnipro River after weeks of Ukrainian advances in the south. The city\'s liberation is met with jubilation by civilians who had lived under occupation for eight months.',
      quote: { text: '"Kherson is ours. The whole country celebrates it."', source: 'Zelenskyy, Nov 11, 2022' },
      image: 'Ukraine_War_Images/08_kherson_battle_map.png',
      tension: 8, type: 'liberation' },
    { date: 'Jun 6, 2023', event: 'Kakhovka Dam Destruction',
      detail: 'The Kakhovka Dam on the Dnipro River is destroyed, unleashing catastrophic flooding across Kherson Oblast. Dozens killed, tens of thousands evacuated, and massive ecological damage. Ukraine and Russia blame each other. The dam\'s destruction complicates Ukraine\'s planned counteroffensive and reshapes the southern front line.',
      quote: { text: '"The destruction of the Kakhovka dam is the biggest man-made environmental disaster in Europe in decades."', source: 'Ursula von der Leyen, European Commission President, Jun 2023' },
      image: 'Ukraine_War_Images/07_luhansk_power_plant.jpg',
      tension: 10, type: 'disaster' },
    { date: 'Jun–Nov 2023', event: 'Ukrainian Counteroffensive',
      detail: 'Ukraine launches a long-anticipated counteroffensive across the southern front, targeting the Russian-occupied Zaporizhzhia corridor. The offensive achieves territorial gains but progresses slowly against heavily fortified Russian defensive lines (the "Surovikin Line") — fields of minefields, trenches, and anti-tank obstacles. Robotyne is recaptured but the main objective of reaching the Sea of Azov is not achieved.',
      quote: { text: '"We are moving forward, step by step. Every metre costs lives, but every metre is worth it."', source: 'Zelenskyy, Aug 2023' },
      image: 'Ukraine_War_Images/09_ukrainian_artillery.jpg',
      tension: 8, type: 'offensive' },
    { date: '2024', event: 'Attritional Warfare — F-16s & Long-Range Strikes',
      detail: 'The war enters an attritional phase. F-16 fighter jets arrive in Ukraine in mid-2024. Ukraine develops long-range drone capability, striking oil refineries and military targets deep inside Russia. Russia maintains pressure along the front, capturing Avdiivka and pushing toward Chasiv Yar. Both sides struggle with manpower and ammunition. Western aid is delayed by US congressional debates.',
      quote: { text: '"Victory is not a single battle. Victory is the ability to outlast the enemy."', source: 'Oleksandr Syrskyi, Commander-in-Chief of Ukrainian Armed Forces, 2024' },
      image: 'Ukraine_War_Images/04_russian_mtlb_z_mark.jpg',
      tension: 8, type: 'attrition' },
    { date: '2025', event: 'Diplomatic Shifts & Negotiation Attempts',
      detail: 'Multiple international mediation efforts intensify. Saudi Arabia, Turkey, and the UAE host preliminary talks. The conflict remains deadlocked militarily with Russia controlling ~18% of Ukrainian territory. European defence spending surges. Ukraine receives security guarantees from several NATO members. The prospect of EU accession negotiations officially opens.',
      quote: null,
      image: 'Ukraine_War_Images/19_civilian_evacuation_irpin.jpg',
      tension: 7, type: 'diplomacy' },
    { date: '2026', event: 'The War Today',
      detail: 'The war continues. The front line remains active but stable in most sectors. Ukraine has become one of the most heavily militarised nations in Europe. Russia\'s economy is on a war footing. The conflict\'s trajectory hinges on Western political will, Russian casualties, Ukrainian military capacity, and the evolving US-China-Russia strategic triangle.',
      quote: null,
      image: 'Ukraine_War_Images/06_russian_bombardment_kharkiv.jpg',
      tension: 7, type: 'ongoing' },
  ],

  simulation: [
    {
      title: 'Human Cost',
      subtitle: 'Cumulative Civilian & Military Casualties',
      value: 500000,
      unit: '+',
      visualType: 'count',
      description: 'Estimated combined casualties including dead and wounded on both sides. The UN confirms over 10,500 civilian deaths; independent estimates range higher. Military casualties on both sides are classified but widely estimated in the hundreds of thousands.',
      gradient: 'linear-gradient(135deg, #0057B7, #FFD700)',
      source: 'UN OHCHR; Ukrainian General Staff; Russian MOD statements (disputed)',
    },
    {
      title: 'Displacement Crisis',
      subtitle: 'Europe\'s Largest Refugee Crisis Since WWII',
      value: '11.9M',
      unit: '',
      visualType: 'displacement',
      items: ['8.2M Refugees Abroad', '3.7M Internally Displaced'],
      description: 'Over 11.9 million Ukrainians — roughly a third of the pre-war population — have been forced from their homes. Nearly 8.2 million have fled abroad (mainly to Poland, Germany, and Czechia). Another 3.7 million are internally displaced within Ukraine, unable to return to occupied or destroyed homes.',
      gradient: 'linear-gradient(135deg, #0057B7, #1e3a5f)',
      source: 'UNHCR (2024); IOM Ukraine Displacement Report (2024)',
    },
    {
      title: 'Economic Devastation',
      subtitle: 'Estimated Damage to Ukrainian Infrastructure',
      value: '500B',
      unit: 'USD',
      visualType: 'count',
      description: 'Estimated total cost of reconstruction for Ukraine. Over 2 million housing units damaged or destroyed. Ports, railways, power plants, and industrial sites — including Azovstal in Mariupol — have been systematically targeted. Ukraine\'s GDP contracted by 29% in 2022, recovering partially by 2024.',
      gradient: 'linear-gradient(135deg, #1e3a5f, #FFD700)',
      source: 'World Bank Ukraine Rapid Damage and Needs Assessment (2024)',
    },
    {
      title: 'Weapons Expenditure',
      subtitle: 'Estimated Daily Cost of War for Russia',
      value: '900M',
      unit: '/day',
      visualType: 'count',
      description: 'Estimated daily cost of the invasion for Russia — including ammunition, fuel, personnel, equipment losses, and replenishment. For Ukraine, the daily cost is approximately $100-150M, heavily subsidised by Western aid. The war has consumed an estimated $1.5T+ in global economic impact.',
      gradient: 'linear-gradient(135deg, #c0392b, #0057B7)',
      source: 'Kiel Institute for the World Economy; Ukraine MOD estimates',
    },
  ],

  players: [
    {
      name: 'Volodymyr Zelenskyy',
      role: 'President of Ukraine',
      trait: 'From comedian to wartime leader — rallying national and international support',
      quote: '"The fight is here. I need ammunition, not a ride."',
      theoryLink: 'Transformational Leadership — crisis-forged identity as national symbol',
      riskDimensions: [
        { label: 'Resolve', value: 95 },
        { label: 'Diplomacy', value: 90 },
        { label: 'Risk Acceptance', value: 85 },
        { label: 'Global Influence', value: 88 },
      ],
      opCode: 'P-1: Politics as existential defence | I-1: Maximise international support | Risk: High — personal presence on front line',
      source: 'IR knowledge base; multiple diplomatic sources',
    },
    {
      name: 'Vladimir Putin',
      role: 'President of Russia',
      trait: 'Authoritarian gambler — willing to accept high costs for strategic objectives',
      quote: '"The collapse of the Soviet Union was the greatest geopolitical catastrophe of the 20th century."',
      theoryLink: 'Offensive Realism (Mearsheimer) — great power competition as structural imperative',
      riskDimensions: [
        { label: 'Resolve', value: 90 },
        { label: 'Diplomacy', value: 40 },
        { label: 'Risk Acceptance', value: 95 },
        { label: 'Global Influence', value: 60 },
      ],
      opCode: 'P-1: Politics as zero-sum power struggle | I-1: Use force to revise the status quo | Risk: Very High — operationalised nuclear threats',
      source: 'IR knowledge base; Mearsheimer (2014/2022); Russian foreign policy statements',
    },
    {
      name: 'Valerii Zaluzhnyi',
      role: 'Commander-in-Chief of Ukrainian Armed Forces (2021–2024)',
      trait: 'The architect of Ukraine\'s military transformation and defensive strategy',
      quote: '"We are not just fighting for our territory. We are fighting for the rules-based world order."',
      theoryLink: 'Adaptive Military Doctrine — learning, decentralisation, technological innovation',
      riskDimensions: [
        { label: 'Resolve', value: 90 },
        { label: 'Diplomacy', value: 50 },
        { label: 'Risk Acceptance', value: 75 },
        { label: 'Global Influence', value: 70 },
      ],
      source: 'IR knowledge base; Zaluzhnyi foreign policy articles (2023)',
    },
    {
      name: 'Joe Biden',
      role: 'President of the United States (2021–2025)',
      trait: 'Architect of the Western alliance — resupply, intelligence, and diplomatic coalition',
      quote: '"Putin is counting on us to lose our resolve. He is counting on NATO to fracture. He is wrong."',
      theoryLink: 'Liberal Institutionalism — strengthened NATO, expanded alliances, security guarantees',
      riskDimensions: [
        { label: 'Resolve', value: 85 },
        { label: 'Diplomacy', value: 90 },
        { label: 'Risk Acceptance', value: 55 },
        { label: 'Global Influence', value: 85 },
      ],
      opCode: 'P-1: Politics as managed competition | I-1: Build coalitions to contain aggression | Risk: Moderate — calibrated escalation management',
      source: 'White House statements; NATO summit communiqués (2022–2024)',
    },
    {
      name: 'NATO & European Union',
      role: 'Institutional Response',
      trait: 'Collective defence and economic pressure — sanctions, aid, and enlargement',
      quote: '"We will support Ukraine for as long as it takes."',
      theoryLink: 'Neoliberal Institutionalism — alliance cohesion and regime complexity in action',
      riskDimensions: [
        { label: 'Resolve', value: 80 },
        { label: 'Diplomacy', value: 85 },
        { label: 'Risk Acceptance', value: 45 },
        { label: 'Global Influence', value: 75 },
      ],
      riskLabels: ['NATO Resolve', 'Sanctions Cohesion', 'Escalation Caution', 'Global Reach'],
      source: 'NATO Strategic Concept (2022); EU Council decisions (2022–2024)',
    },
  ],

  theories: [
    {
      model: '—',
      name: 'Offensive Realism',
      icon: '🌐',
      tag: 'Mearsheimer (2001/2014)',
      explanation: 'Great powers seek to maximise their relative power in an anarchic system. Russia\'s invasion is explained as a structural response to NATO expansion — a great power acting to prevent a rival alliance from encroaching on its perceived sphere of influence. Mearsheimer predicted the conflict in 2014.',
      application: 'Russia\'s invasion is an offensive realist play: prevent Ukraine from joining NATO, re-establish a buffer zone, and demonstrate great power resolve. The theory explains the "why" of the invasion but struggles to explain Russia\'s miscalculations and Ukraine\'s resistance.',
      color: '#1e3a5f',
      reference: 'Mearsheimer (2014). "Why the Ukraine Crisis Is the West\'s Fault"; IR knowledge base',
    },
    {
      model: '—',
      name: 'Defensive Realism & Security Dilemma',
      icon: '🔄',
      tag: 'Jervis (1978) / Waltz (1979)',
      explanation: 'States seek security, not dominance. But the security dilemma means one state\'s defensive measures appear offensive to another. NATO\'s eastward expansion was framed by the West as defensive (protecting new democracies). Russia perceived the same expansion as an existential offensive threat.',
      application: 'The security dilemma intensified after 2014: NATO reinforced Eastern Europe → Russia perceived encirclement → Russia invaded → NATO further reinforced. The spiral of mistrust created the structural conditions for war, even if neither side sought it deliberately.',
      color: '#2E86C1',
      reference: 'Jervis (1978). "Cooperation Under the Security Dilemma"; IR knowledge base',
    },
    {
      model: '—',
      name: 'Liberal Institutionalism',
      icon: '🏛️',
      tag: 'Keohane & Nye (1977/2012)',
      explanation: 'International institutions facilitate cooperation, constrain aggression, and create frameworks for peace. Democratic states are less likely to fight each other (Democratic Peace Theory). NATO and the EU have responded to the invasion with unprecedented sanctions, aid, and institutional adaptation.',
      application: 'NATO transformed from a "brain-dead" alliance (Macron, 2019) to a revitalised defensive coalition. Finland and Sweden joined NATO. The EU granted Ukraine candidate status. Liberal institutionalism explains the Western response, but cannot explain why institutions failed to prevent the war in the first place.',
      color: '#FFD700',
      reference: 'Democratic Peace Theory; NATO Strategic Concept (2022); IR knowledge base',
    },
    {
      model: '—',
      name: 'Constructivism',
      icon: '🧠',
      tag: 'Wendt (1992) / Finnemore & Sikkink (1998)',
      explanation: 'State interests are shaped by identity, norms, and ideas — not just material power. The war is fundamentally about identity: Ukraine\'s European identity vs Russia\'s imperial identity. The conflict is a clash of national narratives — "Ukrainian nationhood" versus "Russkii Mir" (Russian World).',
      application: 'Ukraine\'s resistance is driven by a national identity forged in the crucible of revolution (Euromaidan 2014) and war. Russia\'s invasion is motivated by a narrative of historical grievance and civilisational destiny. Constructivism explains why the war is so intense: it is a war about who Ukrainians are and what Russia should be.',
      color: '#8E44AD',
      reference: 'Wendt (1992). "Anarchy Is What States Make of It"; IR knowledge base',
    },
    {
      model: '—',
      name: 'Prospect Theory',
      icon: '🎲',
      tag: 'Kahneman & Tversky (1979)',
      explanation: 'Decision makers are risk-averse when facing gains and risk-acceptant when facing losses. Putin, facing NATO expansion (a perceived loss of Russia\'s buffer zone and status), became risk-acceptant and chose war. Zelenskyy, facing existential loss (annihilation of his state), accepted extraordinary risks.',
      application: 'Putin in the domain of loss: Russia\'s relative decline, NATO expansion, loss of Ukraine as a client state → gamble on war. Zelenskyy in the domain of loss: annihilation of his nation → accept any risk to survive. Both leaders\' actions — often labelled "irrational" — become predictable under Prospect Theory.',
      color: '#D4AC0D',
      reference: 'Kahneman & Tversky (1979). "Prospect Theory"; CFP Module 5 — Leaders & Psychology (IR2416)',
    },
    {
      model: '—',
      name: 'Democratic Peace Theory',
      icon: '☮️',
      tag: 'Kant (1795) / Doyle (1983)',
      explanation: 'Liberal democracies rarely if ever go to war with each other. The theory suggests that democratic institutions, shared norms, and economic interdependence create a "zone of peace." The Russia-Ukraine war tests the theory: Ukraine is democratic, Russia is autocratic. The war confirms the democratic peace — but only if Ukraine wins.',
      application: 'The theory predicts Russia\'s aggression (autocracy attacking democracy) but also predicts Ukraine\'s resilience (democracies mobilise more effectively, inspire greater international solidarity). It raises a troubling question: does the democratic peace depend on democracy prevailing?',
      color: '#16A085',
      reference: 'Doyle (1983). "Kant, Liberal Legacies, and Foreign Affairs"; IR knowledge base',
    },
    {
      model: '—',
      name: 'Just War Theory',
      icon: '⚖️',
      tag: 'Walzer (1977) / Augustine & Aquinas',
      explanation: 'Jus ad Bellum (just cause for war) and Jus in Bello (just conduct within war). Ukraine\'s self-defence against aggression is widely considered a just cause (jus ad bellum). Russia\'s invasion is a textbook case of aggressive war — a violation of the UN Charter and a crime against peace.',
      application: 'Jus in Bello is contested: Russia has committed documented war crimes (Bucha, Mariupol, targeting civilians, torture). Ukraine has also faced allegations of mistreatment of prisoners. The war raises difficult questions about proportionality in modern warfare, the ethics of Western arms provision, and the rights of combatants and civilians.',
      color: '#C0392B',
      reference: 'Walzer (1977). Just and Unjust Wars; International law (UN Charter, Geneva Conventions)',
    },
    {
      model: '—',
      name: 'Two-Level Games & Alliance Politics',
      icon: '♟️',
      tag: 'Putnam (1988) / Snyder (1997)',
      explanation: 'Leaders negotiate simultaneously at the international level (with other states) and domestic level (with their own constituencies). Zelenskyy plays a two-level game: securing Western aid internationally while maintaining Ukrainian morale and managing domestic expectations domestically. Putin balances international isolation against domestic repression.',
      application: 'Western leaders also play two-level games: Biden managed a divided Congress and NATO allies while supporting Ukraine. Putin manages elite factions (siloviki, military commanders, oligarchs) while facing domestic war-weariness. The "forever war" problem emerges from the two-level game: neither leader can compromise without losing domestic support.',
      color: '#2C3E50',
      reference: 'Putnam (1988). "Diplomacy and Domestic Politics"; CFP Module 2 — Levels of Analysis (IR2416)',
    },
  ],

  levels: [
    {
      level: 'Individual',
      icon: '🧠',
      color: '#0057B7',
      focus: 'Leaders, perception, psychology, decision-making',
      question: 'How did Putin and Zelenskyy\'s personalities and beliefs shape the war?',
      explanation: 'Putin\'s resentment of the post-Cold War settlement, his belief in Russian imperial destiny, and his insulated information environment contributed to his decision to invade. Zelenskyy\'s resilience, communication skills, and willingness to stay in Kyiv transformed him into a global symbol of resistance. Their psychological profiles — Putin\'s isolation and overconfidence vs Zelenskyy\'s adaptive leadership — are essential to understanding the war\'s trajectory.',
      application: 'Putin: Prospect Theory (risk-acceptant in domain of loss), operational code (zero-sum struggle), insulated decision-making. Zelenskyy: transformational leadership, charismatic authority, adaptive learning under extreme stress. The war\'s outcome depends significantly on these personal factors.',
      source: 'CFP Module 5 — Leaders & Psychology; IR knowledge base',
    },
    {
      level: 'State / Domestic',
      icon: '🏛️',
      color: '#FFD700',
      focus: 'Domestic politics, institutions, economy, society',
      question: 'How have domestic politics shaped each side\'s strategy?',
      explanation: 'Russia has become a full-scale war economy, repressing dissent and mobilising society. Wagner Group and other private military actors illustrate the hybrid state-private violence characteristic of Putin\'s regime. Ukraine has transformed its society into a war effort: mass mobilisation, decentralised governance, and civil society leading humanitarian response. Electoral cycles in the US and Europe directly affect the flow of weapons.',
      application: 'Putnam\'s Two-Level Game: Zelenskyy must maintain Ukrainian morale while managing international donors. Putin must maintain elite cohesion while hiding war costs from the Russian public. Western leaders face the gap between public support for Ukraine and the political cost of continued funding.',
      source: 'CFP Module 2 — Levels of Analysis; IR knowledge base',
    },
    {
      level: 'International System',
      icon: '🌍',
      color: '#1e3a5f',
      focus: 'Anarchy, polarity, great power competition, global institutions',
      question: 'Why did the war happen in this particular geopolitical context?',
      explanation: 'The end of the Cold War left a security vacuum in Eastern Europe. NATO expansion, Russia\'s relative decline, and the US\'s shifting strategic focus to China created structural conditions for conflict. The war is a crisis of the post-Cold War order — the first major attempt to revise European borders by force since 1945. China\'s position as Russia\'s economic backstop has prevented Russian collapse.',
      application: 'Systemic factors: (1) Unipolar moment ended → multipolar competition returned. (2) NATO enlargement was perceived by Russia as encirclement. (3) The nuclear umbrella created room for conventional war. (4) The UN Security Council was paralysed by Russia\'s veto power. The war is thus a crisis of the institutions and norms of the post-Cold War order itself.',
      source: 'CFP Module 2 — Levels of Analysis; IR knowledge base; Mearsheimer (2014/2022)',
    },
    {
      level: 'Integrated Analysis',
      icon: '🔗',
      color: '#94A3B8',
      focus: 'All three levels working together',
      question: 'Which level offers the most complete explanation?',
      explanation: 'The system set the stage: unipolar collapse, NATO expansion, Russian decline. Domestic politics shaped each side\'s strategic options: Russian authoritarianism enabled the invasion decision; Ukrainian democracy enabled extraordinary societal resistance. Individual leaders determined the timing and execution: Putin\'s hubris and Zelenskyy\'s courage. Neoclassical realism integrates these levels: systemic pressures are filtered through domestic institutions and individual perceptions.',
      application: 'The full picture: System (post-Cold War order collapse + NATO expansion) → State (Russian authoritarianism vs Ukrainian democracy) → Individual (Putin\'s risk-acceptance vs Zelenskyy\'s resilience). No single level is sufficient — the war requires multi-level analysis to understand its causes, conduct, and possible resolution.',
      source: 'CFP Module 2 — Levels of Analysis; Neoclassical Realism (Rose, 1998); IR knowledge base',
    },
  ],

  legacy: [
    {
      title: 'NATO Revitalised & Expanded',
      date: '2022–2026',
      icon: '🛡️',
      description: 'The invasion ended NATO\'s "strategic slumber." Finland and Sweden — historically neutral — joined the alliance. NATO\'s eastern flank was permanently reinforced. Defence spending across Europe surged to Cold War levels. The alliance\'s purpose was redefined in real time.',
      impact: 'NATO transformed from a post-Cold War identity crisis into a cohesive defensive alliance. The "brain death" declared by Macron in 2019 was reversed by fire.',
      source: 'IR knowledge base; NATO Strategic Concept (2022); EU defence initiatives',
    },
    {
      title: 'EU Integration Accelerated',
      date: '2022–2026',
      icon: '🇪🇺',
      description: 'Ukraine was granted EU candidate status in June 2022 — an unprecedented acceleration for a country at war. Accession negotiations formally opened in 2024. The EU also imposed its most severe sanctions regime on Russia, cutting energy dependence and freezing central bank assets.',
      impact: 'The war transformed the EU\'s foreign policy identity — from a primarily economic actor to a geopolitical one with defence and security dimensions.',
      source: 'European Council decisions (2022–2024); IR knowledge base',
    },
    {
      title: 'The Return of Industrial War',
      date: '2022–present',
      icon: '🏭',
      description: 'The war demonstrated that high-intensity conventional warfare between industrialised states is possible in the 21st century. Trench warfare, artillery duels, mass mobilisation, and industrial production have returned to European battlefields. Drones, electronic warfare, and precision munitions coexist with World War I-style infantry tactics.',
      impact: 'Military doctrine worldwide is being rewritten. The era of counterinsurgency and expeditionary warfare is giving way to peer-competitor conventional readiness.',
      source: 'IR knowledge base; Ukrainian General Staff reports; RUSI analyses (2022–2024)',
    },
    {
      title: 'The Sanctions Regime Experiment',
      date: '2022–present',
      icon: '💰',
      description: 'The West imposed the most extensive sanctions ever applied to a major economy — freezing $300B in Russian central bank reserves, restricting technology exports, and capping oil prices. Russia adapted through energy re-routing to China and India, import substitution, and a war economy.',
      impact: 'Sanctions proved powerful but not decisive. The "sanctions from hell" did not collapse the Russian economy or stop the war. This will reshape theories of economic coercion for a generation.',
      source: 'Kiel Institute for the World Economy; Russian economic data; IR knowledge base',
    },
    {
      title: 'Nuclear Threats & Arms Control Erosion',
      date: '2022–present',
      icon: '☢️',
      description: 'Putin\'s explicit nuclear threats during the war — including placing strategic forces on "special combat duty" — broke the post-Cold War taboo on nuclear brinkmanship. The New START treaty was suspended. Arms control infrastructure continues to erode, raising the risk of nuclear proliferation and accidental escalation.',
      impact: 'The war revived nuclear deterrence as a central feature of European security. The risk of nuclear escalation — dismissed since 1991 — is once again a factor in great power calculations.',
      source: 'Deterrence theory; Russian nuclear doctrine statements; IR knowledge base',
    },
    {
      title: 'The Global South & The "Rules-Based Order"',
      date: '2022–present',
      icon: '🌏',
      description: 'The war exposed deep divisions in the international order. Most of the Global South (India, Brazil, South Africa, much of Africa and Southeast Asia) refused to sanction Russia or provide aid to Ukraine. The "rules-based international order" narrative failed to mobilise the non-Western world.',
      impact: 'The war has accelerated the transition to a multipolar order. The West\'s claim to universal values is increasingly contested. The Global South\'s non-alignment will shape post-war international institutions.',
      source: 'UN General Assembly voting records; IR knowledge base; postcolonial IR theory',
    },
  ],

  questions: [
    {
      q: 'Is this war primarily caused by NATO expansion (structure) or Putin\'s ambition (agency)?',
      a: 'The most contested question in IR scholarship on this war. Structuralists (Mearsheimer/Realism) argue NATO expansion was a provocation that left Russia no choice — the security dilemma in action. Agency-focused accounts argue Putin\'s imperial ambitions, authoritarianism, and grievance-driven ideology are the primary cause — many other states faced NATO expansion without invading. The most robust answer: structure created the conditions, agency made the decision. NATO expansion lowered the threshold for war, but Putin chose to cross it.',
      tags: ['Levels of Analysis', 'Realism', 'Causes of War'],
      source: 'IR knowledge base; Mearsheimer (2014/2022); multiple IR perspectives',
    },
    {
      q: 'Why has Ukraine\'s resistance been more effective than Russia expected?',
      a: 'Three factors: (1) Military transformation — Ukraine\'s army had been reformed since 2014 with NATO training, decentralised command, and motivated professional soldiers. (2) Societal mobilisation — civil society, volunteer networks, and a "nation in arms" created resilience that Russia did not anticipate. (3) Western support — real-time intelligence, advanced weapons (HIMARS, Javelin, F-16s), and training decisively improved Ukrainian combat effectiveness. Russia\'s own failures — poor logistics, low morale, corrupt procurement — multiplied Ukraine\'s advantage.',
      tags: ['Military Strategy', 'Resilience', 'Western Aid'],
      source: 'IR knowledge base; RUSI analyses (2022–2024)',
    },
    {
      q: 'Has the West\'s strategy of "as long as it takes" been successful?',
      a: 'Mixed results. Graduated escalation — providing weapons calibrated to avoid escalation with Russia — has prevented NATO-Russia direct confrontation. But it has also prolonged the war, preventing either side from achieving decisive victory. The strategy succeeds at preventing Russian victory but fails at achieving Ukrainian victory. Critics call this "escalation management as indefinite war." The strategy faces growing political sustainability challenges in both the US and Europe.',
      tags: ['Escalation Management', 'NATO Strategy', 'War Termination'],
      source: 'IR knowledge base; NATO statements; US presidential policy documents (2022–2025)',
    },
    {
      q: 'What role has nuclear deterrence played in this war?',
      a: 'Nuclear deterrence has been central and paradoxical. Putin\'s nuclear threats successfully deterred NATO direct intervention — preventing the "no-fly zone" that Ukraine requested. But the threats failed to deter Western weapons supply. This suggests a "stability-instability paradox" at work: strategic nuclear parity enables conventional war at lower levels. The war has damaged the non-proliferation regime: if nuclear states can invade non-nuclear neighbours with impunity, nuclear weapons become more attractive to states feeling threatened.',
      tags: ['Nuclear Deterrence', 'Stability-Instability Paradox', 'Proliferation'],
      source: 'Deterrence theory; Russian nuclear doctrine; IR knowledge base',
    },
    {
      q: 'Can the war end in a negotiated settlement, or is this an existential struggle?',
      a: 'The structure of the conflict makes negotiated settlement extremely difficult. The core issue — Ukraine\'s sovereignty and territorial integrity vs Russia\'s security demands — is non-negotiable for both sides. Crimea and the annexed territories are deal-breakers. Neither Putin nor Zelenskyy can compromise on these without appearing to lose. The war has become existential for both regimes. Historical parallels (WWI, Iran-Iraq) suggest such wars end through exhaustion rather than negotiated compromise.',
      tags: ['War Termination', 'Negotiation', 'Conflict Resolution'],
      source: 'IR knowledge base; Putnam\'s Two-Level Games; historical conflict analysis',
    },
    {
      q: 'Is the "rules-based international order" dead or merely wounded?',
      a: 'The war is the most serious challenge to the post-1945 order since its founding. Russia\'s veto in the UN Security Council has paralysed the primary institution designed to prevent aggressive war. The International Criminal Court has issued arrest warrants for Putin — unprecedented but unenforceable. The West\'s claim to represent universal values is contested by the Global South. However, NATO and the EU have proven more resilient than expected. The order is not dead but transformed — from a US-led unipolar order to a contested, multipolar system with competing normative claims.',
      tags: ['International Order', 'UN System', 'Multipolarity', 'Global South'],
      source: 'IR knowledge base; UN voting records; postcolonial IR; ICIJ/WTO data',
    },
    {
      q: 'What is the feminist IR critique of this war?',
      a: 'Feminist IR scholars (Tickner, Enloe, Cohn) critique how both state-centric security narratives and the media coverage of the war marginalise gendered experiences. Women and children constitute the majority of refugees and displaced persons. Sexual violence has been documented as a weapon of war by Russian forces. Yet the dominant narrative is about tanks, missiles, and great power competition — casting women as passive victims rather than active participants (women serve in the Ukrainian military at unprecedented rates). Feminist IR also critiques the masculinist framing of "toughness" incentives in Western debates — where politicians compete to show who is stronger on Russia, reinforcing escalation dynamics.',
      tags: ['Feminist IR', 'Gender', 'Critical Security Studies'],
      source: 'Feminist IR theory (Tickner, Enloe); UN documentation of conflict-related sexual violence; IR knowledge base',
    },
    {
      q: 'Does the case of Ukraine and Israel/Gaza offer a parallel in the study of asymmetric warfare?',
      a: 'The two conflicts, while vastly different in context, both illustrate the challenges great powers face when smaller adversaries achieve "competitive empowerment" through external support and technological adaptation. Ukraine resists Russia through Western aid, intelligence, and weapons. Hamas (and broader Iranian-aligned networks) resist Israel through tunnel networks, rocket arsenals, and regional proxies. Both conflicts show that military technology alone cannot guarantee victory against a determined adversary with external backing and asymmetric tactics. Both also demonstrate the radicalisation effects of urban warfare and civilian casualties. A key difference: Ukraine fights for territorial sovereignty within an internationally recognised border framework; the Israel-Gaza conflict operates within a contested territorial and legal framework.',
      tags: ['Asymmetric Warfare', 'Comparative Conflict', 'Civilian Harm'],
      source: 'Comparative conflict analysis; IR knowledge base; asymmetric warfare literature',
    },
  ],

  sources: [
    { title: 'Why the Ukraine Crisis Is the West\'s Fault',
      author: 'Mearsheimer, J.J.',
      year: 2014,
      type: 'Article',
      course: 'IR Theory — Realism / Foreign Policy Analysis',
      relevance: 'Seminal offensive realist argument that NATO expansion provoked Russia. Essential structuralist perspective.' },
    { title: 'The Tragedy of Great Power Politics',
      author: 'Mearsheimer, J.J.',
      year: 2001,
      type: 'Book',
      course: 'IR Theory — Realism',
      relevance: 'Foundational text on offensive realism — the theoretical framework for understanding Russian great power behaviour.' },
    { title: 'Cooperation Under the Security Dilemma',
      author: 'Jervis, R.',
      year: 1978,
      type: 'Article',
      course: 'IR Theory — Strategic Studies',
      relevance: 'The security dilemma framework — how defensive measures by one state trigger offensive perceptions in another.' },
    { title: '"Anarchy Is What States Make of It"',
      author: 'Wendt, A.',
      year: 1992,
      type: 'Article',
      course: 'IR Theory — Constructivism',
      relevance: 'The foundational constructivist text — how the "social construction" of identities shapes international conflict and cooperation.' },
    { title: '"Kant, Liberal Legacies, and Foreign Affairs"',
      author: 'Doyle, M.',
      year: 1983,
      type: 'Article',
      course: 'IR Theory — Liberalism',
      relevance: 'Formulation of Democratic Peace Theory — important for analysing the Russia-Ukraine war in the context of regime type.' },
    { title: 'Just and Unjust Wars',
      author: 'Walzer, M.',
      year: 1977,
      type: 'Book',
      course: 'IR Theory — Ethics / Just War',
      relevance: 'The foundational just war theory text — essential for understanding the moral and legal dimensions of the invasion and conduct of the war.' },
    { title: '"Diplomacy and Domestic Politics: The Logic of Two-Level Games"',
      author: 'Putnam, R.',
      year: 1988,
      type: 'Article',
      course: 'IR2416 — Comparative Foreign Policy',
      relevance: 'Essential framework for understanding how domestic politics on all sides constrain and enable international negotiations.' },
    { title: '"Prospect Theory: An Analysis of Decision under Risk"',
      author: 'Kahneman, D. & Tversky, A.',
      year: 1979,
      type: 'Article',
      course: 'IR2416 — Comparative Foreign Policy',
      relevance: 'Behavioural psychology framework for analysing risk-taking decisions by Putin and Zelenskyy.' },
    { title: 'Ukraine Rapid Damage and Needs Assessment',
      author: 'World Bank, EC, UN, Ukrainian Government',
      year: 2024,
      type: 'Report',
      course: 'IR — International Political Economy / Conflict Studies',
      relevance: 'Authoritative damage assessment — economic and infrastructure costs of the war.' },
    { title: 'NATO Strategic Concept',
      author: 'NATO',
      year: 2022,
      type: 'Policy Document',
      course: 'IR — Security Studies / Alliance Politics',
      relevance: 'Defines NATO\'s post-invasion strategic posture — essential for understanding alliance transformation.' },
  ],
};
